config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admin/index', to: 'admin#index', as: 'admin'
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users, only: [:index,:destroy]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  root to: 'conversations#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # before_action :authenticate_user!
  include Accessible
  before_action :check_user


  def index
    @users = User.all
  end


  private


  def user_params
    accessible = [:username, :email] # extend with your own params
    accessible << [:password, :password_confirmation] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end



  def secure_params
    params.require(:user).permit(:name,:email,:password,:city,)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Mailbox", conversations_path, class: "nav-link" %>
            <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
          </li>
          <li class="nav-item">
            <%= link_to('User Login', new_user_session_path,:class => "nav-link")  %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Setting
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <% if user_signed_in? %>

                  <%= link_to('Edit registration', edit_user_registration_path,:class => "dropdown-item") %>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete,:class => "dropdown-item") %>

              <% end %>

              <% if admin_signed_in? %>

                  <%= link_to('Edit registration', edit_admin_registration_path,:class => "dropdown-item") %>
                  <%= link_to('Logout', destroy_admin_session_path, :method => :delete,:class => "dropdown-item") %>

              <% end %>
            </div>
          </li>
        </form>
      </div>
    </nav>

<div class="container pb50 ">
  <div class="row">
    <div class="col-md-12">
      <h4 class="text-center mb30 danger">Users</h4>
      <table class="table">
        <thead>
        <tr class="info">
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <tr class="success">
          <% @users.each do |user| %>
              <td>
                <%= link_to user.name %>
              </td>
              <td>
                <%= link_to user.email%>
              </td>
              <td>
                <!--<!%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button button-xs button-circle button-danger') %>-->
              </td>
        <% end %>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>