config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admin/index', to: 'admin#index', as: 'admin'
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users, only: [:index,:destroy]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  root to: 'conversations#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    if user
      where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
    end
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  include Accessible
  before_action :check_user
  before_action :authenticate_user!

  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    @users = User.all_except(current_user)
  end

  def show
    @conversation = Conversation.find_by(id: params[:id])
    @message = Message.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="px-3" style="background: aliceblue;color: dimgray">Inbox</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 tex-center">
        <h3 class="px-3"><%= link_to conversation.with(current_user).name , conversation_path(conversation)%></h3>
      </div>
      <div class="col-md-12">
        <em class="px-3"><%= conversation.messages.last.body.truncate(50) %></em>
      </div>
    </div>
  </div>
</div>

app/views/conversations/index.html.erb
<div class="section mt-5">
  <div class="container">
    <div class="container pb50 ">
      <div class="row">
        <div class="col-md-8">
          <div>
            <%= render @conversations %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <h4 class="text-center mb30 danger">Users</h4>
            <table class="table table-striped">
              <thead>
              <tr class="info">
                <th>Name</th>
                <th>Email</th>
                <th>Actions</th>
              </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                <tr class="success">
                  <td>
                    <%= link_to user.name, new_message_path(receiver_id: user) %>
                  </td>
                  <td>
                    <%=user.email%>
                  </td>
                  <td>
                    <%= link_to("Delete", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button button-xs button-circle button-danger') %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 style="background: aliceblue;color: dimgray">Chat with  <%= @conversation.with(current_user).name %></h1>
      </div>
        <div class="col-md-12">
          <div class="card p-3" style="max-height: 530px; min-height: 530px;overflow: auto;">
          <div id="conversation-main">
            <div id="conversation-body">
              <%= render @conversation.messages %>
            </div>
          </div>
        </div>
          <%= form_for @message do |f| %>
              <%= hidden_field_tag 'conversation_id', @conversation.id %>
              <%= f.text_area :body,:class => "form-control",:style => "margin-top: -1px"%>
              <div class="row mt-3">
                <div class="col-md-12">
                  <%= f.submit :class => "btn btn-primary"%>
                  <%= link_to('Back', root_path,:class => "mx-5 px-5 btn btn-primary") %>
                </div>
              </div>
        <% end %>
        </div>
    </div>
  </div>
</div>